== Rolling back changes

Image mode systems have a native capability that typically takes more
preparation with package mode operations: the rollback.

Since `+bootc+` unpacks images locally, we still have the previous
version of the host on disk. Our `+v2+` image was unpacked alongside the
original image, then set as the primary target in the bootloader. To
restore the previous version of a package mode system, we’d need to have
set up snapshots before changes were made or refer to an external
backup. With `+bootc+` we have a single command that can revert to the
last booted image.

A missing web page isn’t the sort of issue we’d normally need to recover
from a backup, but this is a lab after all. Let’s go ahead and check for
an available rollback option to get us back to the previous image.

[source,bash,run]
----
sudo bootc status
----

This bottom section of the status output shows the available image
target. You should see our original image, without the `+v2+` tag. To
trigger the rollback, we issue one command.

[source,bash,run]
----
sudo bootc rollback
----

The command should return very fast and the output looks like this:

[source,nocopy]
----
bootfs is sufficient for calculated new size: 0 bytes
Next boot: rollback deployment
----

There are two additional places in the status you can look for
information about what will happen at the next boot. You should see the
value of `+rollbackQueued+` has been updated. This can be useful to
check before restarting a system.

[source,bash,run]
----
sudo bootc status | grep Queued
----

[source,nocopy]
----
rollbackQueued: true
----

You can also check the boot order in the spec block to see what has been
sent to the bootloader. This should match one of `+default+` or
`+rollback+`. The `+default+` order will use the image from the `+spec+`
section of the status.

[source,bash,run]
----
sudo bootc status | grep Order
----

[source,nocopy]
----
bootOrder: rollback
----

Feel free to explore `+bootc status+` further before moving on.

As usual, a reboot is needed to apply changes. After the reboot, the
rollback image will become the booted image, and will also become the
new default in the boot order.

[source,bash,run]
----
sudo reboot
----

While the system reboots and returns to the previous state, let’s dig
into what happened in the Containerfile and explore why our index.html
update didn’t go the way we expected.
