== What happened to our index file?

You can return to the `Builder` tab to explore what happened
to the new index.html file

We didn’t see any errors from the `+podman build+` when we created the
image, so what happened inside the image?

Since bootc images are still standard OCI images, we can test changes by
running the image as a local container. Using standard container tools
gives us new ways to iterate and inspect hosts without needing to
completely install them first.

Let’s launch the container and list the contents of the directory.
Instead of running interactively and attaching a shell, we can just pass
the command we want run to the container as an argument. We’re also
adding the `+--rm+` flag to make sure the container that runs the `+ls+`
command is removed after the command exits.

[source,bash,run,subs=attributes+]
----
podman run --rm registry-{guid}.{domain}/test-bootc:v2 ls /var/www/html
----
....
index.html
....

== Image vs host state

The file is there, so why didn’t it show up on the host? In
https://www.redhat.com/en/introduction-to-image-mode-for-red-hat-enterprise-linux-interactive-lab[the
image mode basics lab], we discussed how `+/etc+` is treated in image
mode. The `+/var+` hierarchy is also treated specially.

[cols=",,",options="header",]
|===
|directory |owner |bootc action
|/usr |image |overwrite
|/etc |host |merge
|/var |host |ignore
|===

The `+/var+` directory is considered by `+bootc+` to be controlled by
the host as local state. Since we want to manage web content at build
time and version it with the image, we’ll need to move it somewhere
`+bootc+` will control.

== Versioning files with the image

Let’s look at a new Containerfile to see how we can do that. Look at the new `+RUN+` command that uses the `+heredoc+` format to wrap several lines.

[source,bash,run]
----
cat Containerfile.index
----
[source,dockerfile,nocopy]
----
FROM registry.redhat.io/rhel10/rhel-bootc:10.0 

ADD etc /etc 

RUN dnf install -y httpd 
RUN systemctl enable httpd

RUN echo "New application coming soon!" > /var/www/html/index.html

RUN <<EOF # <1>
    mv /var/www /usr/share/www # <2>
    sed -i 's-/var/www-/usr/share/www-' /etc/httpd/conf/httpd.conf
EOF
----
<1> The `heredoc` section using `EOF` as the delimiter
<2> The commands to be exectued by the `RUN` directive

Outside of a lab, you'd likely put the `echo` command that 
creates our `index.html` file inside the `heredoc` instead of including as
a separate layer.  The `heredoc` results in a single layer and is an alternative
to combining shell commands with the `&` operator.

The first command in this block will move the directories and files
installed by Apache to a new directory under `+/usr+`. The second will
update the htttpd config file to change the default document root to our
new directory. 

Since we haven’t made any changes on our bootc host to this file in
`+/etc+`, this change will be applied by `+bootc+`. If you had made
local changes to the httpd config, you may need to create a drop-in file
or use some other means to update the Apache config.

== Use podman to build the image.

We can pass this new file to the `+podman build+` command with the
`+-f+` option and we’ll also give it a `+v3+` tag. Adding this kind of
versioning semantics can help folks understand what’s current in a
series of updated images.

[source,bash,run,subs=attributes+]
----
podman build -t registry-{guid}.{domain}/test-bootc:v3 -f Containerfile.index
----

Let’s test the new image for our new file location the same way we did
earlier, by running the container locally.

[source,bash,run,subs=attributes+]
----
podman run --rm registry-{guid}.{domain}/test-bootc:v3 ls /usr/share/www/html
----

Now that we’re sure we have the changes we need, we can push it to the
registry. Once again, note how only the changed layers need to be added
to the registry even though we changed directory contents and created a
new tag.

[source,bash,run,subs=attributes+]
----
podman push registry-{guid}.{domain}/test-bootc:v3
----

== Switch the VM to our newest version

To apply this update, return to the the `Image mode host` tab.

Just like in the other exercises, we can use `+bootc switch+` to change
to the image we just created with the updated Apache config.

[source,bash,run,subs=attributes+]
----
bootc switch registry-{guid}.{domain}/test-bootc:v3
----

Check that the new image has been staged for the next boot.

[source,bash,run]
----
bootc status
----

You can also check the boot order in the spec block to see what has been
sent to the bootloader. Notice it’s back to `+default+`.

[source,bash,run]
----
bootc status | grep Order
----

Let’s go ahead and restart the system one last time to get our changes.

[source,bash,run]
----
reboot
----

Once the system has completed rebooting, you can log back in by clicking `reconnect` or the Refresh button next to the tab name.

What about our new placeholder index page?

[source,bash,run]
----
curl localhost
----

We have a new docroot that is controlled from the image. We can use this
idea with any software or other content we want to ensure is part of our
standard build rather than managed at runtime on a host.

You’ve now explored how to change the image that a host is tracking,
gained some insights into the differences between directory states, and
been able to roll back from an image update. This should provide a good
basis to explore image mode further on your own!
