---
# Registry-specific firewall rules
# Note: AgnosticD provides defaults for common ports (80, 443, 8080, SSH, etc.)

egress:
  - ports:
      - protocol: TCP
        port: 5000
    to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: registry 

ingress:
  - ports:
      - protocol: TCP
        port: 5000
