---
# By default egress traffic is not allowed, define below the ports allowed.

egress:
  - ports:
      - protocol: TCP
        port: 443
  - to:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher
  - ports:
      - protocol: TCP
        port: 5000
  - to:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher
ingress:
  - from:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher
#
# The following lines are suggested based on Instruqt's allow_external_ingress fields:
# rhel:
#   - http
#   - https
#   - high-ports
