egress:
  - ports:
      - protocol: TCP
        port: 5000
    to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: bootc-registry
  - ports:
      - protocol: TCP
        port: 443

ingress:
  - ports:
      - protocol: TCP
        port: 5000
    from:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher