---
# By default egress traffic is not allowed, define below the ports allowed.

egress:
  - ports:
      - protocol: TCP
        port: 443

# Modeled on default SSH egress rule
  - to:
    - podSelector:
        matchLabels:
          kubevirt.io: virt-launcher
    ports:
    - port: 443  # Allow HTTPS between VMs


    
#
# The following lines are suggested based on Instruqt's allow_external_ingress fields:
# rhel:
#   - http
#   - https
#   - high-ports
