---
virtualmachines:
  - name: "builder"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 4
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    packages:
      - podman
      - skopeo
  - name: "imrhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
