---
virtualmachines:
  - name: "builder"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 4
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    packages:
      - podman
      - skopeo
    services:
      - name: builder-http
        ports:
          - port: 5000
            protocol: TCP
            targetPort: 5000
            name: builder-http
    routes:
      - name: builder-http
        host: builder
        service: builder-http
        targetPort: 5000
        tls: false

  - name: "imrhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 2
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
